---
# tasks file for docker-traefik
- name: Create basepath.
  file:
    path: "{{ traefik_basepath }}"
    state: directory
    owner: "{{ traefik_basepath_owner }}"
    group: "{{ traefik_basepath_group }}"
    mode:  "{{ traefik_basepath_mode }}"
  when: traefik_create_directories

- name: Create directories for bind volumes.
  file:
    path: "{{ traefik_basepath }}/{{ item.name }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ traefik_directories }}"
  when: traefik_create_directories

- name: Send templates.
  ansible.builtin.template:
    src: "{{ item.src_name }}"
    dest: "{{ traefik_basepath }}/{{ item.dest_name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ traefik_templates }}"
